Rakshit-gen/Slanine

- app/dashboard/history/page.tsx
- components/ui/dialog.tsx
- package-lock.json
- package.json
Added the history page using shadcn cards and dialogs
<br/>
<br/>
To keep all the card sizes uniform I added a button to view the full content
<br/>
<br/>
Made sure it looks fine in light mode
<br/>
<br/>
<br/>
Made sure it is responsive as well
<br/>
<br/>
> added history-page

- app/layout.tsx
- next-sitemap.config.js
- package.json
- public/robots.txt
> added:: Meta Tags, Robots.txt, and Sitemap for Improved SEO

- app/dashboard/history/page.tsx
Fixed issue #16
Adjusted max width to accomodate more code and make it scrollable otherwise
> fixed overflowing content bug

- app/not-found.tsx
> added:: Custom 404 Page for Better User Experience

- .gitignore
- app/dashboard/_components/SearchSection.tsx
- components/InfiniteCards2.tsx
- components/ui/infinitecards.tsx
> fixed layout overflow

- app/page.tsx
- components/InfiniteCards.tsx
- components/ModeToggle.tsx
Changed working og theme toggle button
Closes #25 
https://github.com/user-attachments/assets/8fa2c036-0086-4ab4-842a-cf96c247adc1
> Theme toggle changed

- app/page.tsx
- components/Pricing.tsx
Fixed Hero section and also getting hydration error, thats why created 2 commits one for hero section and another for hydration error in Pricing component
> #31 hero section text fix

- components/Footer.tsx
I have successfully changed the twitter logo to X logo you can check that and merge it, assign it to me and put relevent labels: gssoc 2024 ext, hacktoberfest, and level.
issue #40 
@Rakshit-gen Please review this PR
> Changed the twitter logo to X logo

- app/dashboard/_components/Header.tsx
- app/dashboard/_components/SearchSection.tsx
- app/dashboard/_components/SideNav.tsx
- app/dashboard/_components/TemplateCard.tsx
- app/dashboard/_components/TemplateListSection.tsx
- app/dashboard/_components/UsageTrack.tsx
- app/dashboard/layout.tsx
- components/ui/infinitecards.tsx
- package-lock.json
- package.json
- tailwind.config.ts
Closes #4 
Improved ui of dashboard
> improved ui of dashboard

- app/billing/layout.tsx
- app/billing/page.tsx
- app/dashboard/_components/SideNav.tsx
- app/dashboard/layout.tsx
- app/dashboard/page.tsx
- app/page.tsx
Closes #24 
Improved billing page:
Light mode:
Dark Mode:
> improved billing page

- app/layout.tsx
- app/page.tsx
- components/ScrollToTopButton.tsx
done check once done some changes and added button file not deleted any logic in files
> Scroll BottomToUp button

- CONTRIBUTORS.md
- README.md
fixed #50 
@Rakshit-gen 
pls check
> added contributors.md

- components/Footer.tsx
> added github link to the footer

- app/billing/layout.tsx
- app/billing/page.tsx
- app/dashboard/_components/Header.tsx
- app/dashboard/_components/SearchSection.tsx
- app/dashboard/_components/SideNav.tsx
- app/dashboard/_components/TemplateListSection.tsx
- app/dashboard/_components/UsageTrack.tsx
- app/dashboard/history/page.tsx
- app/dashboard/layout.tsx
- app/dashboard/settings/[[...settings]]/page.tsx
- app/page.tsx
- components/Billingcards.tsx
- components/Pricing.tsx
> resolved responsiveness issue on mobile devices

- components/Footer.tsx
This pull request introduces enhancements to the footer section of the website, aimed at improving user experience and accessibility. Key changes include:
Enhanced navigation: Improved organization and labeling of footer links for easier navigation.
Increased accessibility: Implemented accessibility best practices to ensure the footer is usable by users with disabilities.
Improved visual design: Enhanced the footer's appearance for a more visually appealing and consistent look.
By incorporating these changes, the footer section now provides a more intuitive and user-friendly experience for website visitors..    It refers to the issue : #58 . Thank you
> Enhance Footer Section for Improved User Experience

- components/ScrollToTopButton.tsx
I have smoothness in the BackToTop Components
Before and After
https://github.com/user-attachments/assets/40798295-af02-43d1-a1de-bea818e11abb
Completd #60
> B2T Fixes | Issue #60

- app/(auth)/sign-in/[[...sign-in]]/page.tsx
- app/(data)/Templates.tsx
- app/billing/page.tsx
- app/dashboard/_components/SearchSection.tsx
- app/dashboard/_components/SideNav.tsx
- app/dashboard/_components/TemplateCard.tsx
- app/dashboard/_components/TemplateListSection.tsx
- app/dashboard/_components/UsageTrack.tsx
- app/dashboard/content/_components/FormSection.tsx
- app/dashboard/content/_components/OutputSection.tsx
- app/dashboard/history/page.tsx
- app/not-found.tsx
- app/page.tsx
- components/Billingcards.tsx
- components/Footer.tsx
- components/Passers.tsx
- components/Pricing.tsx
- components/ScrollToTopButton.tsx
- package-lock.json
Closes #54 
Improved performance of site
1. removed unwanted imports
2. refactored code
3. implemented lazy loading
Screenshots:
attached in issue #54
> Performance Enhancement

- app/page.tsx
- components/FAQ.tsx
- package-lock.json
This PR introduces a new FAQ section to the application, designed to provide users with answers to common questions while dynamically adapting its style based on the selected theme (light or dark mode). The implementation utilizes `lucide-react` icons to enhance the user interface.
- **Dynamic Theming**: The FAQ section adjusts its colors based on the user's selected theme, providing a seamless experience in both light and dark modes.
- **Interactive FAQ Items**: Users can click on questions to reveal or hide answers, improving engagement and accessibility of information.
- **Responsive Design**: The layout is optimized for various screen sizes, ensuring usability on both desktop and mobile devices.
This PR addresses **issue #71**, which focused on implementing a dynamic FAQ section that …
> FAQ Section

- .github/workflow/pr-checker.yaml
Closes #74 
**Usage:**
1. When a pull request is created or edited, the workflow automatically triggers.
2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`Fixes , Close, Closes, Closed , Fix , Fixed , Resolve , Resolves #Issue_number`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.
**_Note_**: Kindly add all the labels added to the issue, to this PR!
@Rakshit-gen
> Implement GitHub PR Issue Checker Workflow

- app/api/subscribe/route.ts
- components/Footer.tsx
- package-lock.json
- package.json
fixes #69 
added backend service using nodemailer and integrated with the frontend, user receives mails on the input mail ids.
> add email service for stay updated

- .github/workflow/issue_closed_opened.yml
- .github/workflow/pr_merged.yaml
- .github/workflow/pr_raise.yml
Closes #79 
1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**
Using this workflows makes you'r repo more interactive ! @Rakshit-gen 
_**Note**_: Add all the labels and assign me to this PR !!
> Github actions for more connectivity!

- components/FAQ.tsx
fixes #78 
This PR adds transition to the FAQ section on the home page.
https://github.com/user-attachments/assets/3304993f-466e-48d1-a928-b0fb1ef30697
> Add transition to FAQ section.

- CONTRIBUTORS.md
Hi ! @Rakshit-gen ,
I've made some enhancements to the project structure, including a dedicated section for project organization, a detailed pull request process, and clearer guidelines for issue reporting. I hope you find these changes beneficial.
Could you please add the labels "gesso-ext" and "hacktoberfest" and merge the pull request? Thank you!
> Documentation: UPDATE Of Contributing.md #84

- app/layout.tsx
- components/ScrollToTopButton.tsx
closes #94
added a chatbot to the website that provides instant answers to user inquiries
https://github.com/user-attachments/assets/2ff0fc9f-ef45-4f41-8aec-680e6535cb6e
> added chatbot for enhanced user experience

- README.md
ADDED TABLE OF CONTENT ON THE README FILE
ISSUE #109 
CLOSE #109 
Description :
Including a Table of Contents (ToC) in your README file is essential for improving navigation and enhancing the user experience. A well-structured ToC allows users to quickly find the information they need without scrolling through the entire document. This is especially beneficial for larger projects with extensive documentation, as it provides an overview of the content and helps users locate specific sections efficiently. Moreover, a ToC promotes better organization and clarity, making the README more accessible to new and experienced contributors. Streamlining the navigation process encourages greater engagement with the documentation and fosters a sense of professionalism in the project.
> Update README.md ADDED TABLE OF CONTENT ON THE README FILE

- components/FAQ.tsx
closes #97 
after:
https://github.com/user-attachments/assets/eb4ed185-48ab-4d58-9c47-0671c4cd7141
before:
@Rakshit-gen please review this pr. Thanks!
> fixed padding in faq section

- components/Pricing.tsx
Fix: the main page responsiveness #126 
closes issue no - #126 
now the page will be responsive even for smaller displays.
>  Fix: the main page responsiveness #126 

- components/ScrollToTopButton.tsx
Fix: the subscribe to our newsletter is inaccessible #127 
Now the subscribe button is accessible in mobile devices.
Closes issue #127 
And i have also improved the code.
add labels and merge please.
>  Fix: the subscribe to our newsletter is inaccessible #127 

- app/(data)/Templates.tsx
https://github.com/user-attachments/assets/2322c6a7-0fc9-490a-af39-7442e27fe7df
@Rakshit-gen please review this pr thanks!
> added new ai tools for 

- app/page.tsx
- components/ProgressBar.tsx
- tailwind.config.ts
Fixes : #163 
**Changes**:
1. Created components/ProgressBar.tsx : Added a progress bar here
2. Added the "ProgressBar" component in the file : "app/page.tsx"
3. Added the "glowingBar" animation configuration in the file "tailwind.config.ts"
**Demo**:
https://www.loom.com/share/7a81bce3768440848380604ce11ffdf3?sid=d6cddd56-ff8c-4bb1-807a-007d529da580
> "Added animated progress bar"

- app/billing/layout.tsx
- app/dashboard/history/page.tsx
- app/dashboard/page.tsx
- app/dashboard/settings/[[...settings]]/page.tsx
- app/page.tsx
- components/Preloader.tsx
- package-lock.json
- package.json
Closes #57 
Added preloader to: 
Dashboard, 
history, 
billing, 
setting
> Added custom preloader to pages
